### ISSUE TITLE
Observium SVG

### ISSUE THREAD

**Issue by nzkller** [loganmarchione/homelab-svg-assets#11]
Hi, 

As discussed in Reddit, here is the Observium SVG.

Thank you :)

![observium](https://user-images.githubusercontent.com/18606875/231528094-9ab220ca-96cd-4c6a-a585-ee1f3b1af85c.svg)

**Comment by loganmarchione** [comment]
Do you have a link for where you found this SVG?

**Comment by loganmarchione** [comment]
Ah, this SVG is just an encoded PNG file. I'm only adding pure SVGs into this repo.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="450px" height="550px" viewBox="0 0 450 550" enable-background="new 0 0 450 550" xml:space="preserve">  <image id="image0" width="450" height="550" x="0" y="0"
    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAcIAAAImCAYAAADAJYpMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAB
R3pUWHRSYXcgcHJvZmlsZSB0eXBlIHhtcAAAKJFtUkFyBCEIvPuKPMGhEfQ5zqi3VOWY56dxtjbZ
...
...
...
```

**Comment by nzkller** [comment]
Hi Logan,

No, I don't have a link.

I used a software to convert png into svg. 

Pure SVG converters were giving me a very weird image.

Sorry about that, didn't further.

Thank you for checking.
