### ISSUE TITLE
Crafty 4 Icon

### ISSUE THREAD

**Issue by AnonymousX86** [loganmarchione/homelab-svg-assets#22]
- [crafty-controller](https://gitlab.com/crafty-controller/crafty-4/-/blob/99d5871827f0025137251bd10bfc7b2af8518f51/app/frontend/static/assets/images/crafty-logo-square.svg)

**Comment by loganmarchione** [comment]
Sorry for the delay, I added this in `0.3.4`. 

https://github.com/loganmarchione/homelab-svg-assets/commit/7644aad45061f9bc31d53e800fdbd61dd4b9d3ba
