### ISSUE TITLE
Request for Tvheadend and Antennas

### ISSUE THREAD

**Issue by rmoreRojoli** [loganmarchione/homelab-svg-assets#28]
Hi,
Can you add the logos of Tvheadend and Antennas?
Here are the project links:
https://github.com/tvheadend/tvheadend
https://github.com/jfarseneau/antennas

**Comment by loganmarchione** [comment]
I can't find a SVG for Tvheadend. Do you have one? I can only find PNGs.

Antennas was added in 0.3.8.

https://github.com/loganmarchione/homelab-svg-assets/releases/tag/0.3.8

**Comment by rmoreRojoli** [comment]
I am not sure how I missed that one, I did a search for it...
I found this one: https://worldvectorlogo.com/logo/tvheadend

**Comment by loganmarchione** [comment]
This was added in 0.3.9.
