### ISSUE TITLE
Request: Add Maintainerr

### ISSUE THREAD

**Issue by DataBitz** [loganmarchione/homelab-svg-assets#33]
### Name

Maintainerr

### Website

https://maintainerr.info

### Official SVG file for icon

https://[raw.githubusercontent.com/jorenn92/Maintainerr/main/ui/public/logo_icon.svg](https://raw.githubusercontent.com/jorenn92/Maintainerr/main/ui/public/logo_icon.svg)

**Comment by loganmarchione** [comment]
Unfortunately all of those SVGs are actually just PNGs inside. You can open one with a text editor to see the PNG data.

**Comment by loganmarchione** [comment]
Closing this for now.
