### ISSUE TITLE
Request: Beszel

### ISSUE THREAD

**Issue by DragonHeart69** [loganmarchione/homelab-svg-assets#39]
### Name

henrygd/beszel

### Website

https://github.com/henrygd/beszel

### Official SVG file for icon

https://github.com/henrygd/beszel/blob/main/beszel/site/public/static/favicon-green.svg
https://github.com/henrygd/beszel/blob/main/beszel/site/public/static/favicon-red.svg

**Comment by loganmarchione** [comment]
Added in `0.4.2`.
