### ISSUE TITLE
other icons

### ISSUE THREAD

**Issue by DragonHeart69** [loganmarchione/homelab-svg-assets#5]
Hello Logan,

I cloned your repo & added extra icons. I don't think you are waiting for a PR. So I want to let it be known this way that you are welcome to copy the icons from me. I drew over most of the icons myself from the original png/jpg. Some are original from the app's repo.
https://github.com/DragonHeart69/homelab-svg-assets

Kind regards,
Dimitri

**Comment by loganmarchione** [comment]
Dimitri, thanks for this!

I'm still debating if I want to accept PRs into this repo. I'll leave this issue open for now.

**Comment by loganmarchione** [comment]
Closing this for now. I'm accepting PRs and have issues templates in place to request new icons be added.
