### ISSUE TITLE
PNGs

### ISSUE THREAD

**Issue by subcidr** [loganmarchione/homelab-svg-assets#9]
Not all frameworks allow for easy rendering of .svg files, so a folder of the same icons as pngs would be nice ✨
I used a cmd-line tool to achieve this, all pngs should be in good quality; [https://github.com/ElijahHW/homelab-svg-assets](https://github.com/ElijahHW/homelab-svg-assets).

**Comment by loganmarchione** [comment]
I appreciate the idea, but I want to keep this repo SVG-only. I'm happy for you to keep up a fork that has PNGs, and you can also check out [this repo](https://github.com/walkxcode/dashboard-icons/tree/main) for more PNGs.
